name: veracode-build

on:
  push:
    branches:
      - feature/*
      - develop
      - main

  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build and Publish
        run: |
          set -e
          echo "🔎 Searching for .csproj..."
          csproj_file=$(find . -name "*.csproj" -print -quit)
          if [ -z "$csproj_file" ]; then
            echo "::error::No .csproj file found"
            exit 1
          fi
          rm -rf veracode-upload app.zip
          dotnet publish "$csproj_file" -c Release -o ./veracode-upload --no-self-contained
          if [ -z "$(ls -A ./veracode-upload)" ]; then
            echo "::error::Publish step did not produce output"
            exit 1
          fi
          cd veracode-upload
          zip -r ../app.zip .
          cd ..
          ls -lh app.zip

      - name: Upload package for log
        uses: actions/upload-artifact@v4
        with:
          name: veracode-artifact
          path: app.zip

  build-docker-image:
    needs: build
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request' && startsWith(github.event.pull_request.head.ref, 'feature/')
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/verademo-net:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/verademo-net:${{ github.sha }}

      - name: List images
        run: docker images

  veracode-sandbox-feature-pr-develop:
    needs: build
    if: |
      github.event_name == 'pull_request' && startsWith(github.event.pull_request.head.ref, 'feature/')
    uses: ./.github/workflows/veracode-sand-box.yml
    secrets: inherit
    permissions:
      contents: read
      actions: read
      issues: write
      security-events: write
    with:
      veracode_app_profile_name: 'verademo-net'
      veracode_sandbox_name: 'feature-pr-develop-sandbox'
      create_profile: true
      create_sandbox: true

  veracode-sandbox-feature:
    needs: build
    if: startsWith(github.ref_name, 'feature/')
    uses: ./.github/workflows/veracode-sand-box.yml
    secrets: inherit
    permissions:
      contents: read
      actions: read
      issues: write
      security-events: write
    with:
      veracode_app_profile_name: 'verademo-net'
      veracode_sandbox_name: 'feature-sandbox'
      create_profile: true
      create_sandbox: true

  veracode-iac-scan:
    needs: build
    if: startsWith(github.ref_name, 'feature/')
    uses: ./.github/workflows/veracode-iac-scan.yml
    secrets: inherit
    with:
      scan_type: directory
      scan_source: ./
      format_result: json

  veracode-iac-scan_image:
    needs: build-docker-image
    if: |
      github.event_name == 'pull_request' && startsWith(github.event.pull_request.head.ref, 'feature/')
    uses: ./.github/workflows/veracode-iac-scan.yml
    secrets: inherit
    with:
      scan_type: image
      scan_source: ghcr.io/${{ github.repository }}/verademo-net:${{ github.sha }}
      format_result: table

  veracode-policy-scan:
    needs: build
    if: |
       github.event_name == 'pull_request' && github.event.pull_request.head.ref == 'develop'
    uses: ./.github/workflows/veracode-policy-scan.yml
    secrets: inherit
    permissions:
      contents: read
      actions: read
      issues: write
      security-events: write
    with:
      veracode_app_profile_name: 'verademo-net'