name: veracode-build-autopackage

on:
  push:
    branches:
      - feature/*
      - develop
      - main

  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Veracode CLI
        run: curl -fsS https://tools.veracode.com/veracode-cli/install | sh

      - name: Set Veracode credentials
        run: |
          echo "VERACODE_API_KEY_ID=${{ secrets.VERACODE_API_ID }}" >> $GITHUB_ENV
          echo "VERACODE_API_KEY_SECRET=${{ secrets.VERACODE_API_KEY }}" >> $GITHUB_ENV

      - name: Veracode Auto-Package
        run: |
          set -e
          PROJECT_PATH="."
          OUTPUT_DIR="veracode-output"

          mkdir -p $OUTPUT_DIR

          ./veracode package \
            --source "$PROJECT_PATH" \
            --output "$OUTPUT_DIR" \
            --trust \
            --verbose

          echo "📦 Generated artifacts:"
          ls -lh $OUTPUT_DIR

      
      - name: Upload package for Veracode
        uses: actions/upload-artifact@v4
        with:
          name: veracode-artifact
          path: veracode-output/*.zip

  build-docker-image:
    needs: build
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request' && startsWith(github.event.pull_request.head.ref, 'feature/')
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/verademo-net:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/verademo-net:${{ github.sha }}

      - name: List images
        run: docker images

  veracode-pipeline-scan:
    needs: build
    if: startsWith(github.ref_name, 'feature/')
    uses: ./.github/workflows/veracode-pipeline-scan.yml
    secrets: inherit
    permissions:
      contents: read
      actions: read
      issues: write
      security-events: write
    with:
      veracode_policy_name: 'Veracode Recommended Very High + SCA'
      json_output: true
      output_file: veracode-results.json
      fail_build: false
      verbose: true

  veracode-sandbox-feature:
    needs: build
    if: startsWith(github.ref_name, 'feature/')
    uses: ./.github/workflows/veracode-sand-box.yml
    secrets: inherit
    permissions:
      contents: read
      actions: read
      issues: write
      security-events: write
    with:
      veracode_app_profile_name: 'verademo-net'
      veracode_sandbox_name: 'feature-sandbox'
      create_profile: true
      create_sandbox: true
      scan_timeout: 0

  veracode-iac-scan:
    needs: build
    if: startsWith(github.ref_name, 'feature/')
    uses: ./.github/workflows/veracode-iac-scan.yml
    secrets: inherit
    with:
      scan_type: directory
      scan_source: .
      format_result: json

  veracode-iac-scan_image:
    needs: build-docker-image
    if: |
      github.event_name == 'pull_request' && startsWith(github.event.pull_request.head.ref, 'feature/')
    uses: ./.github/workflows/veracode-iac-scan.yml
    secrets: inherit
    with:
      scan_type: image
      scan_source: ghcr.io/${{ github.repository }}/verademo-net:${{ github.sha }}
      format_result: json

  veracode-sandbox-develop:
    needs: build
    if: |
      github.event_name == 'pull_request' && startsWith(github.event.pull_request.head.ref, 'feature/')
    uses: ./.github/workflows/veracode-sand-box.yml
    secrets: inherit
    permissions:
      contents: read
      actions: read
      issues: write
      security-events: write
    with:
      veracode_app_profile_name: 'verademo-net'
      veracode_sandbox_name: 'feature-develop-sandbox'
      create_profile: true
      create_sandbox: true

  veracode-policy-scan:
    needs: build
    if: |
      github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'develop'
    uses: ./.github/workflows/veracode-policy-scan.yml
    secrets: inherit
    permissions:
      contents: read
      actions: read
      issues: write
      security-events: write
    with:
      veracode_app_profile_name: 'verademo-net'